version: '2'
services:

  discovery-service:
    image: discovery-service:latest
    ports:
      - 8761:8761

  database:
    image: mysql:8-oracle
    ports:
      - 3306:3306
    environment:
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=admin
    - MYSQL_DATABASE=streamify
    - MYSQL_ROOT_PASSWORD=admin

  gateway:
    image: gateway:latest
    ports:
      - 8082:8082
    depends_on:
     - discovery-service
    environment:
      - SERVICE_DISCOVERY_HOST=discovery-service
      - SERVICE_DISCOVERY_PORT=8761

  identity-service:
    image: identity-service:latest
    ports:
      - 8083:8083
    depends_on:
      - database
      - gateway
      - discovery-service
    environment:
      - DB_HOST=database
      - DB_NAME=streamify
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - SERVICE_DISCOVERY_HOST=discovery-service
      - SERVICE_DISCOVERY_PORT=8761
      
  video-service:
    image: video-service:latest
    ports:
      - 8081:8081
    depends_on:
      - database
      - gateway
      - discovery-service
      - identity-service
      - kafka
    environment:
      - DB_HOST=database
      - DB_NAME=streamify
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - SERVICE_DISCOVERY_HOST=discovery-service
      - SERVICE_DISCOVERY_PORT=8761
      - KAFKA_HOST=kafka
      - SPRING_PROFILES_ACTIVE=docker
      - KAFKA_PORT=9092

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  notification-service:
    image: notification-service:latest
    ports:
      - 8086:8086
    depends_on:
      - database
      - gateway
      - discovery-service
      - video-service
      - identity-service
      - kafka
    environment:
      - DB_HOST=database
      - DB_NAME=streamify
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - SERVICE_DISCOVERY_HOST=discovery-service
      - SERVICE_DISCOVERY_PORT=8761
      - KAFKA_HOST=kafka
      - SPRING_PROFILES_ACTIVE=docker
      - KAFKA_PORT=9092

  frontend:
    image: streamify-fe:latest
    ports:
      - 3000:3000
    depends_on:
     - discovery-service
     - database
     - gateway
     - identity-service
     - video-service

